baseURL: https://tip-topych.github.io/
languageCode: en-us
title: Lazy Blog
theme: PaperMod
paginate: 5

sectionPagesMenu: main

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

enableRobotsTXT: true
buildDrafts: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Lazy Blog
  description: "Ленивый блог"
  keywords: [Blog, Portfolio, DIY, Lazy Kraken]
  author: Lazy Kraken
  # author: ["Me", "You"] # multiple authors
  images: ["construction-tools-flatlay.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, light
  disableThemeToggle: false
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
 
  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    # safari_pinned_tab:  "/safari-pinned-tab.svg"
 
  editPost:
    URL: "https://github.com/Tip-Topych/tip-topych.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
    


  remark42:
    enable: true
    host: "https://remark42.lazykraken.ru"
    site_id: "tip-topych.github.io"
    theme: "dark"
    locale: "ru"
    components: "['embed', 'last-comments', 'counter']"
    show_email_subscription: false
    simple_view: true